NUM_CODEWORDS = {
    1: {'L': {   'total_data_cws': 19,
                    'total_ec_cws': 7,
                    'ec_cws_per_block': 7,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 19,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'M': {   'total_data_cws': 16,
                    'total_ec_cws': 10,
                    'ec_cws_per_block': 10,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 16,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'Q': {   'total_data_cws': 13,
                    'total_ec_cws': 13,
                    'ec_cws_per_block': 13,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 13,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'H': {   'total_data_cws': 9,
                    'total_ec_cws': 17,
                    'ec_cws_per_block': 17,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 9,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0}},
    2: {   'L': {   'total_data_cws': 34,
                    'total_ec_cws': 10,
                    'ec_cws_per_block': 10,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 34,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'M': {   'total_data_cws': 28,
                    'total_ec_cws': 16,
                    'ec_cws_per_block': 16,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 28,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'Q': {   'total_data_cws': 22,
                    'total_ec_cws': 22,
                    'ec_cws_per_block': 22,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 22,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'H': {   'total_data_cws': 16,
                    'total_ec_cws': 28,
                    'ec_cws_per_block': 28,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 16,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0}},
    3: {   'L': {   'total_data_cws': 55,
                    'total_ec_cws': 15,
                    'ec_cws_per_block': 15,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 55,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'M': {   'total_data_cws': 44,
                    'total_ec_cws': 26,
                    'ec_cws_per_block': 26,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 44,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'Q': {   'total_data_cws': 34,
                    'total_ec_cws': 36,
                    'ec_cws_per_block': 18,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 17,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'H': {   'total_data_cws': 26,
                    'total_ec_cws': 44,
                    'ec_cws_per_block': 22,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 13,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0}},
    4: {   'L': {   'total_data_cws': 80,
                    'total_ec_cws': 20,
                    'ec_cws_per_block': 20,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 80,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'M': {   'total_data_cws': 64,
                    'total_ec_cws': 36,
                    'ec_cws_per_block': 18,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 32,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'Q': {   'total_data_cws': 48,
                    'total_ec_cws': 52,
                    'ec_cws_per_block': 26,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 24,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'H': {   'total_data_cws': 36,
                    'total_ec_cws': 64,
                    'ec_cws_per_block': 16,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 9,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0}},
    5: {   'L': {   'total_data_cws': 108,
                    'total_ec_cws': 26,
                    'ec_cws_per_block': 26,
                    'g1_blocks': 1,
                    'data_cws_per_g1_block': 108,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'M': {   'total_data_cws': 86,
                    'total_ec_cws': 48,
                    'ec_cws_per_block': 24,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 43,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'Q': {   'total_data_cws': 62,
                    'total_ec_cws': 72,
                    'ec_cws_per_block': 18,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 15,
                    'g2_blocks': 2,
                    'data_cws_per_g2_block': 16},
           'H': {   'total_data_cws': 46,
                    'total_ec_cws': 88,
                    'ec_cws_per_block': 22,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 11,
                    'g2_blocks': 2,
                    'data_cws_per_g2_block': 12}},
    6: {   'L': {   'total_data_cws': 136,
                    'total_ec_cws': 36,
                    'ec_cws_per_block': 18,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 68,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'M': {   'total_data_cws': 108,
                    'total_ec_cws': 64,
                    'ec_cws_per_block': 16,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 27,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'Q': {   'total_data_cws': 76,
                    'total_ec_cws': 96,
                    'ec_cws_per_block': 24,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 19,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'H': {   'total_data_cws': 60,
                    'total_ec_cws': 112,
                    'ec_cws_per_block': 28,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 15,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0}},
    7: {   'L': {   'total_data_cws': 156,
                    'total_ec_cws': 40,
                    'ec_cws_per_block': 20,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 78,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'M': {   'total_data_cws': 124,
                    'total_ec_cws': 72,
                    'ec_cws_per_block': 18,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 31,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'Q': {   'total_data_cws': 88,
                    'total_ec_cws': 108,
                    'ec_cws_per_block': 18,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 14,
                    'g2_blocks': 4,
                    'data_cws_per_g2_block': 15},
           'H': {   'total_data_cws': 66,
                    'total_ec_cws': 130,
                    'ec_cws_per_block': 26,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 13,
                    'g2_blocks': 1,
                    'data_cws_per_g2_block': 14}},
    8: {   'L': {   'total_data_cws': 194,
                    'total_ec_cws': 48,
                    'ec_cws_per_block': 24,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 97,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'M': {   'total_data_cws': 154,
                    'total_ec_cws': 88,
                    'ec_cws_per_block': 22,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 38,
                    'g2_blocks': 2,
                    'data_cws_per_g2_block': 39},
           'Q': {   'total_data_cws': 110,
                    'total_ec_cws': 132,
                    'ec_cws_per_block': 22,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 18,
                    'g2_blocks': 2,
                    'data_cws_per_g2_block': 19},
           'H': {   'total_data_cws': 86,
                    'total_ec_cws': 156,
                    'ec_cws_per_block': 26,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 14,
                    'g2_blocks': 2,
                    'data_cws_per_g2_block': 15}},
    9: {   'L': {   'total_data_cws': 232,
                    'total_ec_cws': 60,
                    'ec_cws_per_block': 30,
                    'g1_blocks': 2,
                    'data_cws_per_g1_block': 116,
                    'g2_blocks': 0,
                    'data_cws_per_g2_block': 0},
           'M': {   'total_data_cws': 182,
                    'total_ec_cws': 110,
                    'ec_cws_per_block': 22,
                    'g1_blocks': 3,
                    'data_cws_per_g1_block': 36,
                    'g2_blocks': 2,
                    'data_cws_per_g2_block': 37},
           'Q': {   'total_data_cws': 132,
                    'total_ec_cws': 160,
                    'ec_cws_per_block': 20,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 16,
                    'g2_blocks': 4,
                    'data_cws_per_g2_block': 17},
           'H': {   'total_data_cws': 100,
                    'total_ec_cws': 192,
                    'ec_cws_per_block': 24,
                    'g1_blocks': 4,
                    'data_cws_per_g1_block': 12,
                    'g2_blocks': 4,
                    'data_cws_per_g2_block': 13}},
    10: {   'L': {   'total_data_cws': 274,
                     'total_ec_cws': 72,
                     'ec_cws_per_block': 18,
                     'g1_blocks': 2,
                     'data_cws_per_g1_block': 68,
                     'g2_blocks': 2,
                     'data_cws_per_g2_block': 69},
            'M': {   'total_data_cws': 216,
                     'total_ec_cws': 130,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 43,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 44},
            'Q': {   'total_data_cws': 154,
                     'total_ec_cws': 192,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 6,
                     'data_cws_per_g1_block': 19,
                     'g2_blocks': 2,
                     'data_cws_per_g2_block': 20},
            'H': {   'total_data_cws': 122,
                     'total_ec_cws': 224,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 6,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 2,
                     'data_cws_per_g2_block': 16}},
    11: {   'L': {   'total_data_cws': 324,
                     'total_ec_cws': 80,
                     'ec_cws_per_block': 20,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 81,
                     'g2_blocks': 0,
                     'data_cws_per_g2_block': 0},
            'M': {   'total_data_cws': 254,
                     'total_ec_cws': 150,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 1,
                     'data_cws_per_g1_block': 50,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 51},
            'Q': {   'total_data_cws': 180,
                     'total_ec_cws': 224,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 22,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 23},
            'H': {   'total_data_cws': 140,
                     'total_ec_cws': 264,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 3,
                     'data_cws_per_g1_block': 12,
                     'g2_blocks': 8,
                     'data_cws_per_g2_block': 13}},
    12: {   'L': {   'total_data_cws': 370,
                     'total_ec_cws': 96,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 2,
                     'data_cws_per_g1_block': 92,
                     'g2_blocks': 2,
                     'data_cws_per_g2_block': 93},
            'M': {   'total_data_cws': 290,
                     'total_ec_cws': 176,
                     'ec_cws_per_block': 22,
                     'g1_blocks': 6,
                     'data_cws_per_g1_block': 36,
                     'g2_blocks': 2,
                     'data_cws_per_g2_block': 37},
            'Q': {   'total_data_cws': 206,
                     'total_ec_cws': 260,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 20,
                     'g2_blocks': 6,
                     'data_cws_per_g2_block': 21},
            'H': {   'total_data_cws': 158,
                     'total_ec_cws': 308,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 7,
                     'data_cws_per_g1_block': 14,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 15}},
    13: {   'L': {   'total_data_cws': 428,
                     'total_ec_cws': 104,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 107,
                     'g2_blocks': 0,
                     'data_cws_per_g2_block': 0},
            'M': {   'total_data_cws': 334,
                     'total_ec_cws': 198,
                     'ec_cws_per_block': 22,
                     'g1_blocks': 8,
                     'data_cws_per_g1_block': 37,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 38},
            'Q': {   'total_data_cws': 244,
                     'total_ec_cws': 288,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 8,
                     'data_cws_per_g1_block': 20,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 21},
            'H': {   'total_data_cws': 180,
                     'total_ec_cws': 352,
                     'ec_cws_per_block': 22,
                     'g1_blocks': 12,
                     'data_cws_per_g1_block': 11,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 12}},
    14: {   'L': {   'total_data_cws': 461,
                     'total_ec_cws': 120,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 3,
                     'data_cws_per_g1_block': 115,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 116},
            'M': {   'total_data_cws': 365,
                     'total_ec_cws': 216,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 40,
                     'g2_blocks': 5,
                     'data_cws_per_g2_block': 41},
            'Q': {   'total_data_cws': 261,
                     'total_ec_cws': 320,
                     'ec_cws_per_block': 20,
                     'g1_blocks': 11,
                     'data_cws_per_g1_block': 16,
                     'g2_blocks': 5,
                     'data_cws_per_g2_block': 17},
            'H': {   'total_data_cws': 197,
                     'total_ec_cws': 384,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 11,
                     'data_cws_per_g1_block': 12,
                     'g2_blocks': 5,
                     'data_cws_per_g2_block': 13}},
    15: {   'L': {   'total_data_cws': 523,
                     'total_ec_cws': 132,
                     'ec_cws_per_block': 22,
                     'g1_blocks': 5,
                     'data_cws_per_g1_block': 87,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 88},
            'M': {   'total_data_cws': 415,
                     'total_ec_cws': 240,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 5,
                     'data_cws_per_g1_block': 41,
                     'g2_blocks': 5,
                     'data_cws_per_g2_block': 42},
            'Q': {   'total_data_cws': 295,
                     'total_ec_cws': 360,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 5,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 7,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 223,
                     'total_ec_cws': 432,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 11,
                     'data_cws_per_g1_block': 12,
                     'g2_blocks': 7,
                     'data_cws_per_g2_block': 13}},
    16: {   'L': {   'total_data_cws': 589,
                     'total_ec_cws': 144,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 5,
                     'data_cws_per_g1_block': 98,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 99},
            'M': {   'total_data_cws': 453,
                     'total_ec_cws': 280,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 7,
                     'data_cws_per_g1_block': 45,
                     'g2_blocks': 3,
                     'data_cws_per_g2_block': 46},
            'Q': {   'total_data_cws': 325,
                     'total_ec_cws': 408,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 15,
                     'data_cws_per_g1_block': 19,
                     'g2_blocks': 2,
                     'data_cws_per_g2_block': 20},
            'H': {   'total_data_cws': 253,
                     'total_ec_cws': 480,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 3,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 13,
                     'data_cws_per_g2_block': 16}},
    17: {   'L': {   'total_data_cws': 647,
                     'total_ec_cws': 168,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 1,
                     'data_cws_per_g1_block': 107,
                     'g2_blocks': 5,
                     'data_cws_per_g2_block': 108},
            'M': {   'total_data_cws': 507,
                     'total_ec_cws': 308,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 10,
                     'data_cws_per_g1_block': 46,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 47},
            'Q': {   'total_data_cws': 367,
                     'total_ec_cws': 448,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 1,
                     'data_cws_per_g1_block': 22,
                     'g2_blocks': 15,
                     'data_cws_per_g2_block': 23},
            'H': {   'total_data_cws': 283,
                     'total_ec_cws': 532,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 2,
                     'data_cws_per_g1_block': 14,
                     'g2_blocks': 17,
                     'data_cws_per_g2_block': 15}},
    18: {   'L': {   'total_data_cws': 721,
                     'total_ec_cws': 180,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 5,
                     'data_cws_per_g1_block': 120,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 121},
            'M': {   'total_data_cws': 563,
                     'total_ec_cws': 338,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 9,
                     'data_cws_per_g1_block': 43,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 44},
            'Q': {   'total_data_cws': 397,
                     'total_ec_cws': 504,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 17,
                     'data_cws_per_g1_block': 22,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 23},
            'H': {   'total_data_cws': 313,
                     'total_ec_cws': 588,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 2,
                     'data_cws_per_g1_block': 14,
                     'g2_blocks': 19,
                     'data_cws_per_g2_block': 15}},
    19: {   'L': {   'total_data_cws': 795,
                     'total_ec_cws': 196,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 3,
                     'data_cws_per_g1_block': 113,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 114},
            'M': {   'total_data_cws': 627,
                     'total_ec_cws': 364,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 3,
                     'data_cws_per_g1_block': 44,
                     'g2_blocks': 11,
                     'data_cws_per_g2_block': 45},
            'Q': {   'total_data_cws': 445,
                     'total_ec_cws': 546,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 17,
                     'data_cws_per_g1_block': 21,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 22},
            'H': {   'total_data_cws': 341,
                     'total_ec_cws': 650,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 9,
                     'data_cws_per_g1_block': 13,
                     'g2_blocks': 16,
                     'data_cws_per_g2_block': 14}},
    20: {   'L': {   'total_data_cws': 861,
                     'total_ec_cws': 224,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 3,
                     'data_cws_per_g1_block': 107,
                     'g2_blocks': 5,
                     'data_cws_per_g2_block': 108},
            'M': {   'total_data_cws': 669,
                     'total_ec_cws': 416,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 3,
                     'data_cws_per_g1_block': 41,
                     'g2_blocks': 13,
                     'data_cws_per_g2_block': 42},
            'Q': {   'total_data_cws': 485,
                     'total_ec_cws': 600,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 15,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 5,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 385,
                     'total_ec_cws': 700,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 15,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 10,
                     'data_cws_per_g2_block': 16}},
    21: {   'L': {   'total_data_cws': 932,
                     'total_ec_cws': 224,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 116,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 117},
            'M': {   'total_data_cws': 714,
                     'total_ec_cws': 442,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 17,
                     'data_cws_per_g1_block': 42,
                     'g2_blocks': 0,
                     'data_cws_per_g2_block': 0},
            'Q': {   'total_data_cws': 512,
                     'total_ec_cws': 644,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 17,
                     'data_cws_per_g1_block': 22,
                     'g2_blocks': 6,
                     'data_cws_per_g2_block': 23},
            'H': {   'total_data_cws': 406,
                     'total_ec_cws': 750,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 19,
                     'data_cws_per_g1_block': 16,
                     'g2_blocks': 6,
                     'data_cws_per_g2_block': 17}},
    22: {   'L': {   'total_data_cws': 1006,
                     'total_ec_cws': 252,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 2,
                     'data_cws_per_g1_block': 111,
                     'g2_blocks': 7,
                     'data_cws_per_g2_block': 112},
            'M': {   'total_data_cws': 782,
                     'total_ec_cws': 476,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 17,
                     'data_cws_per_g1_block': 46,
                     'g2_blocks': 0,
                     'data_cws_per_g2_block': 0},
            'Q': {   'total_data_cws': 568,
                     'total_ec_cws': 690,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 7,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 16,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 442,
                     'total_ec_cws': 816,
                     'ec_cws_per_block': 24,
                     'g1_blocks': 34,
                     'data_cws_per_g1_block': 13,
                     'g2_blocks': 0,
                     'data_cws_per_g2_block': 0}},
    23: {   'L': {   'total_data_cws': 1094,
                     'total_ec_cws': 270,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 121,
                     'g2_blocks': 5,
                     'data_cws_per_g2_block': 122},
            'M': {   'total_data_cws': 860,
                     'total_ec_cws': 504,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 47,
                     'g2_blocks': 14,
                     'data_cws_per_g2_block': 48},
            'Q': {   'total_data_cws': 614,
                     'total_ec_cws': 750,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 11,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 14,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 464,
                     'total_ec_cws': 900,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 16,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 14,
                     'data_cws_per_g2_block': 16}},
    24: {   'L': {   'total_data_cws': 1174,
                     'total_ec_cws': 300,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 6,
                     'data_cws_per_g1_block': 117,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 118},
            'M': {   'total_data_cws': 914,
                     'total_ec_cws': 560,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 6,
                     'data_cws_per_g1_block': 45,
                     'g2_blocks': 14,
                     'data_cws_per_g2_block': 46},
            'Q': {   'total_data_cws': 664,
                     'total_ec_cws': 810,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 11,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 16,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 514,
                     'total_ec_cws': 960,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 30,
                     'data_cws_per_g1_block': 16,
                     'g2_blocks': 2,
                     'data_cws_per_g2_block': 17}},
    25: {   'L': {   'total_data_cws': 1276,
                     'total_ec_cws': 312,
                     'ec_cws_per_block': 26,
                     'g1_blocks': 8,
                     'data_cws_per_g1_block': 106,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 107},
            'M': {   'total_data_cws': 1000,
                     'total_ec_cws': 588,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 8,
                     'data_cws_per_g1_block': 47,
                     'g2_blocks': 13,
                     'data_cws_per_g2_block': 48},
            'Q': {   'total_data_cws': 718,
                     'total_ec_cws': 870,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 7,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 22,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 538,
                     'total_ec_cws': 1050,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 22,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 13,
                     'data_cws_per_g2_block': 16}},
    26: {   'L': {   'total_data_cws': 1370,
                     'total_ec_cws': 336,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 10,
                     'data_cws_per_g1_block': 114,
                     'g2_blocks': 2,
                     'data_cws_per_g2_block': 115},
            'M': {   'total_data_cws': 1062,
                     'total_ec_cws': 644,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 19,
                     'data_cws_per_g1_block': 46,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 47},
            'Q': {   'total_data_cws': 754,
                     'total_ec_cws': 952,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 28,
                     'data_cws_per_g1_block': 22,
                     'g2_blocks': 6,
                     'data_cws_per_g2_block': 23},
            'H': {   'total_data_cws': 596,
                     'total_ec_cws': 1110,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 33,
                     'data_cws_per_g1_block': 16,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 17}},
    27: {   'L': {   'total_data_cws': 1468,
                     'total_ec_cws': 360,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 8,
                     'data_cws_per_g1_block': 122,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 123},
            'M': {   'total_data_cws': 1128,
                     'total_ec_cws': 700,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 22,
                     'data_cws_per_g1_block': 45,
                     'g2_blocks': 3,
                     'data_cws_per_g2_block': 46},
            'Q': {   'total_data_cws': 808,
                     'total_ec_cws': 1020,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 8,
                     'data_cws_per_g1_block': 23,
                     'g2_blocks': 26,
                     'data_cws_per_g2_block': 24},
            'H': {   'total_data_cws': 628,
                     'total_ec_cws': 1200,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 12,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 28,
                     'data_cws_per_g2_block': 16}},
    28: {   'L': {   'total_data_cws': 1531,
                     'total_ec_cws': 390,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 3,
                     'data_cws_per_g1_block': 117,
                     'g2_blocks': 10,
                     'data_cws_per_g2_block': 118},
            'M': {   'total_data_cws': 1193,
                     'total_ec_cws': 728,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 3,
                     'data_cws_per_g1_block': 45,
                     'g2_blocks': 23,
                     'data_cws_per_g2_block': 46},
            'Q': {   'total_data_cws': 871,
                     'total_ec_cws': 1050,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 31,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 661,
                     'total_ec_cws': 1260,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 11,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 31,
                     'data_cws_per_g2_block': 16}},
    29: {   'L': {   'total_data_cws': 1631,
                     'total_ec_cws': 420,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 7,
                     'data_cws_per_g1_block': 116,
                     'g2_blocks': 7,
                     'data_cws_per_g2_block': 117},
            'M': {   'total_data_cws': 1267,
                     'total_ec_cws': 784,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 21,
                     'data_cws_per_g1_block': 45,
                     'g2_blocks': 7,
                     'data_cws_per_g2_block': 46},
            'Q': {   'total_data_cws': 911,
                     'total_ec_cws': 1140,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 1,
                     'data_cws_per_g1_block': 23,
                     'g2_blocks': 37,
                     'data_cws_per_g2_block': 24},
            'H': {   'total_data_cws': 701,
                     'total_ec_cws': 1350,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 19,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 26,
                     'data_cws_per_g2_block': 16}},
    30: {   'L': {   'total_data_cws': 1735,
                     'total_ec_cws': 450,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 5,
                     'data_cws_per_g1_block': 115,
                     'g2_blocks': 10,
                     'data_cws_per_g2_block': 116},
            'M': {   'total_data_cws': 1373,
                     'total_ec_cws': 812,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 19,
                     'data_cws_per_g1_block': 47,
                     'g2_blocks': 10,
                     'data_cws_per_g2_block': 48},
            'Q': {   'total_data_cws': 985,
                     'total_ec_cws': 1200,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 15,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 25,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 745,
                     'total_ec_cws': 1440,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 23,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 25,
                     'data_cws_per_g2_block': 16}},
    31: {   'L': {   'total_data_cws': 1843,
                     'total_ec_cws': 480,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 13,
                     'data_cws_per_g1_block': 115,
                     'g2_blocks': 3,
                     'data_cws_per_g2_block': 116},
            'M': {   'total_data_cws': 1455,
                     'total_ec_cws': 868,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 2,
                     'data_cws_per_g1_block': 46,
                     'g2_blocks': 29,
                     'data_cws_per_g2_block': 47},
            'Q': {   'total_data_cws': 1033,
                     'total_ec_cws': 1290,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 42,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 793,
                     'total_ec_cws': 1530,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 23,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 28,
                     'data_cws_per_g2_block': 16}},
    32: {   'L': {   'total_data_cws': 1955,
                     'total_ec_cws': 510,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 17,
                     'data_cws_per_g1_block': 115,
                     'g2_blocks': 0,
                     'data_cws_per_g2_block': 0},
            'M': {   'total_data_cws': 1541,
                     'total_ec_cws': 924,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 10,
                     'data_cws_per_g1_block': 46,
                     'g2_blocks': 23,
                     'data_cws_per_g2_block': 47},
            'Q': {   'total_data_cws': 1115,
                     'total_ec_cws': 1350,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 10,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 35,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 845,
                     'total_ec_cws': 1620,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 19,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 35,
                     'data_cws_per_g2_block': 16}},
    33: {   'L': {   'total_data_cws': 2071,
                     'total_ec_cws': 540,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 17,
                     'data_cws_per_g1_block': 115,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 116},
            'M': {   'total_data_cws': 1631,
                     'total_ec_cws': 980,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 14,
                     'data_cws_per_g1_block': 46,
                     'g2_blocks': 21,
                     'data_cws_per_g2_block': 47},
            'Q': {   'total_data_cws': 1171,
                     'total_ec_cws': 1440,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 29,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 19,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 901,
                     'total_ec_cws': 1710,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 11,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 46,
                     'data_cws_per_g2_block': 16}},
    34: {   'L': {   'total_data_cws': 2191,
                     'total_ec_cws': 570,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 13,
                     'data_cws_per_g1_block': 115,
                     'g2_blocks': 6,
                     'data_cws_per_g2_block': 116},
            'M': {   'total_data_cws': 1725,
                     'total_ec_cws': 1036,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 14,
                     'data_cws_per_g1_block': 46,
                     'g2_blocks': 23,
                     'data_cws_per_g2_block': 47},
            'Q': {   'total_data_cws': 1231,
                     'total_ec_cws': 1530,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 44,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 7,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 961,
                     'total_ec_cws': 1800,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 59,
                     'data_cws_per_g1_block': 16,
                     'g2_blocks': 1,
                     'data_cws_per_g2_block': 17}},
    35: {   'L': {   'total_data_cws': 2306,
                     'total_ec_cws': 570,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 12,
                     'data_cws_per_g1_block': 121,
                     'g2_blocks': 7,
                     'data_cws_per_g2_block': 122},
            'M': {   'total_data_cws': 1812,
                     'total_ec_cws': 1064,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 12,
                     'data_cws_per_g1_block': 47,
                     'g2_blocks': 26,
                     'data_cws_per_g2_block': 48},
            'Q': {   'total_data_cws': 1286,
                     'total_ec_cws': 1590,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 39,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 14,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 986,
                     'total_ec_cws': 1890,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 22,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 41,
                     'data_cws_per_g2_block': 16}},
    36: {   'L': {   'total_data_cws': 2434,
                     'total_ec_cws': 600,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 6,
                     'data_cws_per_g1_block': 121,
                     'g2_blocks': 14,
                     'data_cws_per_g2_block': 122},
            'M': {   'total_data_cws': 1914,
                     'total_ec_cws': 1120,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 6,
                     'data_cws_per_g1_block': 47,
                     'g2_blocks': 34,
                     'data_cws_per_g2_block': 48},
            'Q': {   'total_data_cws': 1354,
                     'total_ec_cws': 1680,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 46,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 10,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 1054,
                     'total_ec_cws': 1980,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 2,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 64,
                     'data_cws_per_g2_block': 16}},
    37: {   'L': {   'total_data_cws': 2566,
                     'total_ec_cws': 630,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 17,
                     'data_cws_per_g1_block': 122,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 123},
            'M': {   'total_data_cws': 1992,
                     'total_ec_cws': 1204,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 29,
                     'data_cws_per_g1_block': 46,
                     'g2_blocks': 14,
                     'data_cws_per_g2_block': 47},
            'Q': {   'total_data_cws': 1426,
                     'total_ec_cws': 1770,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 49,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 10,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 1096,
                     'total_ec_cws': 2100,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 24,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 46,
                     'data_cws_per_g2_block': 16}},
    38: {   'L': {   'total_data_cws': 2702,
                     'total_ec_cws': 660,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 4,
                     'data_cws_per_g1_block': 122,
                     'g2_blocks': 18,
                     'data_cws_per_g2_block': 123},
            'M': {   'total_data_cws': 2102,
                     'total_ec_cws': 1260,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 13,
                     'data_cws_per_g1_block': 46,
                     'g2_blocks': 32,
                     'data_cws_per_g2_block': 47},
            'Q': {   'total_data_cws': 1502,
                     'total_ec_cws': 1860,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 48,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 14,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 1142,
                     'total_ec_cws': 2220,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 42,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 32,
                     'data_cws_per_g2_block': 16}},
    39: {   'L': {   'total_data_cws': 2812,
                     'total_ec_cws': 720,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 20,
                     'data_cws_per_g1_block': 117,
                     'g2_blocks': 4,
                     'data_cws_per_g2_block': 118},
            'M': {   'total_data_cws': 2216,
                     'total_ec_cws': 1316,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 40,
                     'data_cws_per_g1_block': 47,
                     'g2_blocks': 7,
                     'data_cws_per_g2_block': 48},
            'Q': {   'total_data_cws': 1582,
                     'total_ec_cws': 1950,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 43,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 22,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 1222,
                     'total_ec_cws': 2310,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 10,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 67,
                     'data_cws_per_g2_block': 16}},
    40: {   'L': {   'total_data_cws': 2956,
                     'total_ec_cws': 750,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 19,
                     'data_cws_per_g1_block': 118,
                     'g2_blocks': 6,
                     'data_cws_per_g2_block': 119},
            'M': {   'total_data_cws': 2334,
                     'total_ec_cws': 1372,
                     'ec_cws_per_block': 28,
                     'g1_blocks': 18,
                     'data_cws_per_g1_block': 47,
                     'g2_blocks': 31,
                     'data_cws_per_g2_block': 48},
            'Q': {   'total_data_cws': 1666,
                     'total_ec_cws': 2040,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 34,
                     'data_cws_per_g1_block': 24,
                     'g2_blocks': 34,
                     'data_cws_per_g2_block': 25},
            'H': {   'total_data_cws': 1276,
                     'total_ec_cws': 2430,
                     'ec_cws_per_block': 30,
                     'g1_blocks': 20,
                     'data_cws_per_g1_block': 15,
                     'g2_blocks': 61,
                     'data_cws_per_g2_block': 16}}}
